spring:
  application:
    name: Test Back-end for Attornatus
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-admin-password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080